name: 'Terraform Destroy Workspace'
description: 'Destroy all resources in a specific workspace and delete the workspace itself.'

inputs:
  aws-access-key:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region:
    description: 'AWS Region for the provider and backend'
    required: true
  terraform-state-bucket-name:
    description: 'Name of the existing S3 bucket to store Terraform state'
    required: true
  terraform-state-key:
    description: 'Key used for Terraform state'
    required: false
    default: terraform.tfstate
  terraform-files-directory:
    description: 'Path to the directory containing .tf files'
    required: false
    default: '.'
  terraform-workspace-name:
    description: 'The Terraform workspace to use (e.g., dev, prod)'
    required: true
  terraform-variable-values-map:
    description: 'A JSON string of variables to pass to Terraform (e.g., {"bucket_name": "my-site"})'
    required: false
    default: '{}'

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # 1. Create Variables File
    # Even during destroy, Terraform needs input variables to satisfy validation checks.
    - name: Create Variables File
      shell: bash
      working-directory: ${{ inputs.terraform-files-directory }}
      run: |
        echo '${{ inputs.terraform-variable-values-map }}' > destroy.auto.tfvars.json

    # 2. Initialize
    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.terraform-files-directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        terraform init \
          -backend-config="bucket=${{ inputs.terraform-state-bucket-name }}" \
          -backend-config="region=${{ inputs.aws-region }}" \
          -backend-config="key=${{ inputs.terraform-state-key }}"

    # 3. Select Workspace
    # If this fails, the workspace doesn't exist, and the action will stop here (safely).
    - name: Select Workspace
      shell: bash
      working-directory: ${{ inputs.terraform-files-directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: terraform workspace select ${{ inputs.terraform-workspace-name }}

    # 4. Destroy Resources
    - name: Terraform Destroy
      shell: bash
      working-directory: ${{ inputs.terraform-files-directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: terraform destroy -auto-approve

    # 5. Delete Workspace
    # We must switch to 'default' before we can delete the current workspace.
    - name: Delete Workspace
      shell: bash
      working-directory: ${{ inputs.terraform-files-directory }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-key }}
        AWS_REGION: ${{ inputs.aws-region }}
      run: |
        terraform workspace select default
        terraform workspace delete ${{ inputs.terraform-workspace-name }}