name: 'Build Vite App'
description: 'Installs dependencies and compiles a Vite React project from a specific directory'

inputs:
  app-directory:
    description: 'The subdirectory containing the package.json'
    required: true
    default: '.'
  build-directory:
    description: 'The folder name where the build is output (e.g., dist, build)'
    required: false
    default: 'dist'

outputs:
  artifact-path:
    description: "The full path to the built artifacts relative to the repo root"
    value: ${{ steps.set-output.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '${{ inputs.app-directory }}/package-lock.json'

    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ inputs.app-directory }}
        npm ci

    - name: Build Project
      shell: bash
      run: |
        cd ${{ inputs.app-directory }}
        npm run build

    # NEW STEP: Calculate and set the output variable
    - name: Set Artifact Path Output
      id: set-output
      shell: bash
      run: |
        # Construct the full path (e.g., frontend/dist)
        FULL_PATH="${{ inputs.app-directory }}/${{ inputs.build-directory }}"
        
        # Write to $GITHUB_OUTPUT so the main workflow can read it
        echo "path=$FULL_PATH" >> $GITHUB_OUTPUT