name: 'Publish to S3 Bucket'
description: 'Installs dependencies and runs tests for a Vite project'

inputs:  

  aws-access-key:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-key:
    description: 'AWS Secret Access Key'
    required: true
  aws-region: 
    description: 'AWS region which contains the S3 bucket'
    required: true
    default: 'us-west-1'

  artifacts-path:
    description: 'The directory containing the items you want to upload to S3'
    required: true
  
  s3-bucket:
    description: 'The S3 bucket you want to upload to'
    required: true

  s3-destination-path:
    description: 'The S3 bucket path you want to upload to'
    required: true
    default: ''
  
runs:
  using: "composite"
  steps:    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        # role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # Recommended: Use IAM Role
        # OR use standard keys:
        aws-access-key-id: ${{ inputs.aws-access-key }}
        aws-secret-access-key: ${{ inputs.aws-secret-key }}
        aws-region: ${{ inputs.aws-region }}

    # Upload to S3 with the specific path structure
    - name: Upload Reports to S3
      env:
        VERSION: ${{ steps.package-version.outputs.version }}
        RUN_ID: ${{ github.run_number }}
      shell: bash
      run: |
        # Sync Unit Test Report
        aws s3 sync ${{ inputs.artifacts-path }} s3://${{ inputs.s3-bucket }}${{ inputs.s3-destination-path }} --delete      

